# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    image: mysql
    ports:
      - 3306:3306
    command: ["mysqld", "--character-set-server=utf8mb4" , "--collation-server=utf8mb4_unicode_ci"]
    volumes:
      - ./db-volume/entry-point/:/docker-entrypoint-initdb.d/
      # - ./db-volume/conf.d/:/etc/mysql/conf.d/
      - ./db-volume/mysql:/var/lib/mysql:rw
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rd
